### ISSUE TITLE
ValueError: Expected input batch_size (6728) to match target batch_size (128).

### ISSUE THREAD

**Issue by woonhahaha** [woonhahaha/fast-cu-split-decision-cnn#1]
```
Traceback (most recent call last):
  File "train.py", line 73, in <module>
    main(config)
  File "train.py", line 54, in main
    trainer.train()
  File "/home/whyeo/VVCWorkspace/Thesis/fast-cu-split-decision-cnn/base/base_trainer.py", line 63, in train
    result = self._train_epoch(epoch)
  File "/home/whyeo/VVCWorkspace/Thesis/fast-cu-split-decision-cnn/trainer/trainer.py", line 47, in _train_epoch
    loss = self.criterion(output, target)
  File "/home/whyeo/VVCWorkspace/Thesis/fast-cu-split-decision-cnn/model/loss.py", line 11, in ce_loss
    return F.cross_entropy(output, target)
  File "/home/whyeo/anaconda3/envs/deeplab-pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 2021, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/whyeo/anaconda3/envs/deeplab-pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 1836, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (6728) to match target batch_size (128).
```

**Comment by woonhahaha** [comment]
[Solution](https://discuss.pytorch.org/t/valueerror-expected-input-batch-size-324-to-match-target-batch-size-4/24498)
